version : '3'
 
services:
  prom-demo-api:
    image: prom-demo-api
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
    networks:
      - dotnetcorepromgrafana

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorepromgrafana

  grafana: 
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    restart: always
    ports:
      - 3000:3000
    networks:
      - dotnetcorepromgrafana

### put all the networks here
networks:
  dotnetcorepromgrafana: